steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull',
      'gcr.io/ai2-allennlp/allennlp-demo:latest']
  - name: gcr.io/kaniko-project/executor
    args:
      - --destination=gcr.io/ai2-allennlp/allennlp-demo:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run',
      '--entrypoint=',
      'gcr.io/ai2-allennlp/allennlp-demo:$COMMIT_SHA',
      'pytest',
      'tests/']
    timeout: 1000s
timeout: 2000s
images: [
  'gcr.io/ai2-allennlp/allennlp-demo:$COMMIT_SHA',
]
